### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by aawgit** [aawgit/onlineStore#1]
Document the API end points implemented in routes.

**Comment by UddeshJain** [comment]
I would like to, is it still available?

**Comment by aawgit** [comment]
@UddeshJain Yes. It is.

**Comment by UddeshJain** [comment]
Ok, I'll do it.

**Comment by aashaypalliwar** [comment]
I would like to help, is it available?

**Comment by aawgit** [comment]
Hi Aashay,

Yes, its available.

Thanks and best regards,
Akalanka

**Comment by gunishjain** [comment]
Hey, is it still available for contribution?

**Comment by aawgit** [comment]
Hi Gunish,

Yes, Its available.

Thanks and regards,
Akalanka

**Comment by hemantreddy** [comment]
Hey is it still not resolved?

**Comment by mattshin64** [comment]
Hi, is this still available for contribution?

**Comment by aawgit** [comment]
> Hi, is this still available for contribution?

Of course :)

**Comment by dbiradar** [comment]
Hi, I would like to contribute please, if its still available.

**Comment by mcam10** [comment]
Is this still open?
