### ISSUE TITLE
Complete the refactoring of auth router

### ISSUE THREAD

**Issue by aawgit** [aawgit/onlineStore#23]
Refactor https://github.com/aawgit/onlineStore/blob/master/server/src/controller/authentication.controller.js such that its split to controller and service layers like the other 2 controllers, and use ES 6 syntax. A very simple task. Appropriate for beginners.

**Comment by qsingletary** [comment]
@aawgit can you assign this to me?

**Comment by mikeronewman** [comment]
Is this up for grabs still? I'd like to give it a shot today.

**Comment by mooosh-milllie** [comment]
@aawgit is this issue available?

**Comment by Ayboss** [comment]
@aawgit, Hi. is this issue still available? I could give it a go.

**Comment by aawgit** [comment]
> @aawgit, Hi. is this issue still available? I could give it a go.

Yes

**Comment by aawgit** [comment]
> @aawgit is this issue available?

Yes

**Comment by aawgit** [comment]
> @aawgit is it still available ? looks simple and can work on it ASAP

Yes

**Comment by prashantpadhy** [comment]
i would love to work on it is is available?

**Comment by Ayboss** [comment]
> > @aawgit is it still available ? looks simple and can work on it ASAP
> 
> Yes

Hi @aawgit , I created a Pull request for this issue.

**Comment by aawgit** [comment]
Closed the issue after merging https://github.com/aawgit/onlineStore/pull/40.
